#
# Autogenerated by Thrift Compiler (0.9.1)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'

class Doctor
  include ::Thrift::Struct, ::Thrift::Struct_Union
  CLAVE = 1
  NOMBRE = 2
  DIRECCION = 3
  ESPECIALIDAD = 4
  TELEFONO = 5
  FOTO = 6

  FIELDS = {
    CLAVE => {:type => ::Thrift::Types::STRING, :name => 'clave'},
    NOMBRE => {:type => ::Thrift::Types::STRING, :name => 'nombre'},
    DIRECCION => {:type => ::Thrift::Types::STRING, :name => 'direccion'},
    ESPECIALIDAD => {:type => ::Thrift::Types::STRING, :name => 'especialidad'},
    TELEFONO => {:type => ::Thrift::Types::STRING, :name => 'telefono'},
    FOTO => {:type => ::Thrift::Types::STRING, :name => 'foto'}
  }

  def struct_fields; FIELDS; end

  def validate
  end

  ::Thrift::Struct.generate_accessors self
end

