require 'pg'
require 'openssl'

@password = (OpenSSL::Digest.new 'SHA256').digest 'password'
@iv = (OpenSSL::Digest.new 'SHA256').digest 'iv'

def encrypt (data)
  cipher = OpenSSL::Cipher.new 'AES-256-CBC'
  cipher.encrypt
  cipher.key, cipher.iv = @password, @iv
  (cipher.update(data) + cipher.final).unpack('H*')[0]
end

connection = PG::Connection.open dbname: 'hospital', host: 'localhost'

#Inserts
connection.exec "INSERT INTO Doctor VALUES ('#{encrypt 'D01'}', '#{encrypt 'Jorge Ramírez'}'      , '#{encrypt 'Chichonal #76'}'       , '#{encrypt 'Cardiología'}'     , '#{encrypt '7221236445'}');"
connection.exec "INSERT INTO Doctor VALUES ('#{encrypt 'D02'}', '#{encrypt 'Juan Gómez'}'         , '#{encrypt 'Chichonal #80'}'       , '#{encrypt 'Pediatría'}'       , '#{encrypt '7226543562'}');"
connection.exec "INSERT INTO Doctor VALUES ('#{encrypt 'D03'}', '#{encrypt 'Mario Méndez'}'       , '#{encrypt 'Jesus del Monte #85'}' , '#{encrypt 'Cardiología'}'     , '#{encrypt '7223413553'}');"
connection.exec "INSERT INTO Doctor VALUES ('#{encrypt 'D04'}', '#{encrypt 'Jorge Ramírez'}'      , '#{encrypt 'Pico de Orizaba #76'}' , '#{encrypt 'Endocrinología'}'  , '#{encrypt '7222341643'}');"
connection.exec "INSERT INTO Doctor VALUES ('#{encrypt 'D05'}', '#{encrypt 'Antonio González'}'   , '#{encrypt 'Morelos #123'}'        , '#{encrypt 'Pediatría'}'       , '#{encrypt '7221341543'}');"
connection.exec "INSERT INTO Doctor VALUES ('#{encrypt 'D06'}', '#{encrypt 'Manuel Suárez'}'      , '#{encrypt 'V. Carranza #765'}'    , '#{encrypt 'Cardiología'}'     , '#{encrypt '7224326798'}');"
connection.exec "INSERT INTO Doctor VALUES ('#{encrypt 'D07'}', '#{encrypt 'Milton López'}'       , '#{encrypt 'Los Cusis #2181'}'	     , '#{encrypt 'Endocrinología'}'  , '#{encrypt '7226544564'}');"
connection.exec "INSERT INTO Doctor VALUES ('#{encrypt 'D08'}', '#{encrypt 'Pedro Gutiérrez'}'    , '#{encrypt 'Tollocan #32'}' 		 , '#{encrypt 'Traumatología'}'   , '#{encrypt '7228363456'}');"
connection.exec "INSERT INTO Doctor VALUES ('#{encrypt 'D09'}', '#{encrypt 'Fernanda López'}'     , '#{encrypt 'Pensador Mexicano #85'}', '#{encrypt 'Pediatría'}'       , '#{encrypt '7226254453'}');"
connection.exec "INSERT INTO Doctor VALUES ('#{encrypt 'D10'}', '#{encrypt 'Ana Carbajal'}'       , '#{encrypt 'Reforma #123'}'        , '#{encrypt 'Oncología'}'       , '#{encrypt '7222244355'}');"
connection.exec "INSERT INTO Doctor VALUES ('#{encrypt 'D11'}', '#{encrypt 'Ignacio Aguirre'}'    , '#{encrypt 'Chichonal #76'}'       , '#{encrypt 'Cardiología'}'     , '#{encrypt '7226543445'}');"
connection.exec "INSERT INTO Doctor VALUES ('#{encrypt 'D12'}', '#{encrypt 'Manuel Clemente'}'    , '#{encrypt 'Chichonal #80'}'       , '#{encrypt 'Endocrinología'}'  , '#{encrypt '7226545452'}');"
connection.exec "INSERT INTO Doctor VALUES ('#{encrypt 'D13'}', '#{encrypt 'María Infante'}'      , '#{encrypt 'Jesus del Monte #85'}' , '#{encrypt 'Cardiología'}'     , '#{encrypt '7223413713'}');"
connection.exec "INSERT INTO Doctor VALUES ('#{encrypt 'D14'}', '#{encrypt 'Francisco González'}' , '#{encrypt 'Pico de Orizaba #76'}' , '#{encrypt 'Endocrinología'}'  , '#{encrypt '7222341345'}');"
connection.exec "INSERT INTO Doctor VALUES ('#{encrypt 'D15'}', '#{encrypt 'Ramón Sánchez'}'      , '#{encrypt 'Morelos #123'}'        , '#{encrypt 'Medicina General'}', '#{encrypt '7221341433'}');"
connection.exec "INSERT INTO Doctor VALUES ('#{encrypt 'D16'}', '#{encrypt 'Raúl Grande'}'        , '#{encrypt 'V. Carranza #765'}'    , '#{encrypt 'Cardiología'}'     , '#{encrypt '7224326438'}');"
connection.exec "INSERT INTO Doctor VALUES ('#{encrypt 'D17'}', '#{encrypt 'Luis Placencia'}'     , '#{encrypt 'Los Cusis #2181'}'	     , '#{encrypt 'Endocrinología'}'  , '#{encrypt '7221234508'}');"
connection.exec "INSERT INTO Doctor VALUES ('#{encrypt 'D18'}', '#{encrypt 'Felisa Trujillo'}'    , '#{encrypt 'Tollocan #32'}' 		 , '#{encrypt 'Ginecología'}'     , '#{encrypt '7221234553'}');"
connection.exec "INSERT INTO Doctor VALUES ('#{encrypt 'D19'}', '#{encrypt 'Julio Loret'}'        , '#{encrypt 'Pensador Mexicano #85'}', '#{encrypt 'Pediatría'}'       , '#{encrypt '7221234568'}');"
connection.exec "INSERT INTO Doctor VALUES ('#{encrypt 'D20'}', '#{encrypt 'Concepción Santiago'}', '#{encrypt 'Reforma #123'}'        , '#{encrypt 'Cardiología'}'     , '#{encrypt '7221234565'}');"
connection.exec "INSERT INTO Doctor VALUES ('#{encrypt 'D21'}', '#{encrypt 'Yolanda Reina'}'      , '#{encrypt 'Chichonal #76'}'       , '#{encrypt 'Cardiología'}'     , '#{encrypt '7221234596'}');"
connection.exec "INSERT INTO Doctor VALUES ('#{encrypt 'D22'}', '#{encrypt 'Paula López'}'        , '#{encrypt 'Chichonal #80'}'       , '#{encrypt 'Endocrinología'}'  , '#{encrypt '7226543285'}');"
connection.exec "INSERT INTO Doctor VALUES ('#{encrypt 'D23'}', '#{encrypt 'Sergio Villar'}'      , '#{encrypt 'Jesus del Monte #85'}' , '#{encrypt 'Oncología'}'       , '#{encrypt '7223413572'}');"
connection.exec "INSERT INTO Doctor VALUES ('#{encrypt 'D24'}', '#{encrypt 'Teresa Gregori'}'     , '#{encrypt 'Pico de Orizaba #76'}' , '#{encrypt 'Endocrinología'}'  , '#{encrypt '7222341568'}');"
connection.exec "INSERT INTO Doctor VALUES ('#{encrypt 'D25'}', '#{encrypt 'José Sáez'}'          , '#{encrypt 'Morelos #123'}'        , '#{encrypt 'Pediatría'}'       , '#{encrypt '7223413564'}');"
connection.exec "INSERT INTO Doctor VALUES ('#{encrypt 'D26'}', '#{encrypt 'Natalia Osuna'}'      , '#{encrypt 'V. Carranza #765'}'    , '#{encrypt 'Medicina General'}', '#{encrypt '7224326678'}');"
connection.exec "INSERT INTO Doctor VALUES ('#{encrypt 'D27'}', '#{encrypt 'Jesús Gutiérrez'}'    , '#{encrypt 'Los Cusis #2181'}'	     , '#{encrypt 'Endocrinología'}'  , '#{encrypt '7223447655'}');"
connection.exec "INSERT INTO Doctor VALUES ('#{encrypt 'D28'}', '#{encrypt 'Adrián Soto'}'        , '#{encrypt 'Tollocan #32'}' 		 , '#{encrypt 'Pediatría'}'       , '#{encrypt '7224645765'}');"
connection.exec "INSERT INTO Doctor VALUES ('#{encrypt 'D29'}', '#{encrypt 'Laura del Valle'}'    , '#{encrypt 'Pensador Mexicano #85'}', '#{encrypt 'Traumatología'}'   , '#{encrypt '7224635345'}');"
connection.exec "INSERT INTO Doctor VALUES ('#{encrypt 'D30'}', '#{encrypt 'Pablo Quesada'}'      , '#{encrypt 'Reforma #123'}'        , '#{encrypt 'Ginecología'}'     , '#{encrypt '7226537675'}');"

connection.exec "INSERT INTO Paciente VALUES('#{encrypt 'P01'}', '#{encrypt 'Juan Cárdenas' }'   , '#{encrypt 'Av. Alemana #23' }'     , '#{encrypt '7226543285' }');"
connection.exec "INSERT INTO Paciente VALUES('#{encrypt 'P02'}', '#{encrypt 'Roberto Ríos' }'    , '#{encrypt 'Calle Los Pinos #52' }' , '#{encrypt '7226545423' }');"
connection.exec "INSERT INTO Paciente VALUES('#{encrypt 'P03'}', '#{encrypt 'Nicolás Jiménez' }' , '#{encrypt 'Miraflores #123' }'     , '#{encrypt '7229473423' }');"
connection.exec "INSERT INTO Paciente VALUES('#{encrypt 'P04'}', '#{encrypt 'Ruddy Rojo' }'      , '#{encrypt 'Av. V. Carranza #54' }' , '#{encrypt '7224132234' }');"
connection.exec "INSERT INTO Paciente VALUES('#{encrypt 'P05'}', '#{encrypt 'Samuel Medina' }'   , '#{encrypt 'Real del bosque #323' }', '#{encrypt '7223124234' }');"
connection.exec "INSERT INTO Paciente VALUES('#{encrypt 'P06'}', '#{encrypt 'Roberto Suárez' }'  , '#{encrypt 'Calle Los Cedros #65' }', '#{encrypt '7224365422' }');"
connection.exec "INSERT INTO Paciente VALUES('#{encrypt 'P07'}', '#{encrypt 'Jorge Ramírez' }'   , '#{encrypt 'Calacoto #234' }'       , '#{encrypt '7226542457' }');"
connection.exec "INSERT INTO Paciente VALUES('#{encrypt 'P08'}', '#{encrypt 'Patricia Méndez' }' , '#{encrypt 'Calle Beni #22' }'      , '#{encrypt '7226735322' }');"
connection.exec "INSERT INTO Paciente VALUES('#{encrypt 'P09'}', '#{encrypt 'Cristina Medina' }' , '#{encrypt 'Av. Bánzer #443' }'     , '#{encrypt '7222036535' }');"
connection.exec "INSERT INTO Paciente VALUES('#{encrypt 'P10'}', '#{encrypt 'Guido Nayar' }'     , '#{encrypt 'Av. Landívar #55' }'    , '#{encrypt '7223456234' }');"
connection.exec "INSERT INTO Paciente VALUES('#{encrypt 'P11'}', '#{encrypt 'Martha Rodríguez' }', '#{encrypt 'Av. Alemana #23' }'     , '#{encrypt '7224036512' }');"
connection.exec "INSERT INTO Paciente VALUES('#{encrypt 'P12'}', '#{encrypt 'Julia Ríos' }'      , '#{encrypt 'Calle Los Pinos #52' }' , '#{encrypt '7222452342' }');"
connection.exec "INSERT INTO Paciente VALUES('#{encrypt 'P13'}', '#{encrypt 'Maria Ballesteros' }', '#{encrypt 'Miraflores #123' }'     , '#{encrypt '7222034234' }');"
connection.exec "INSERT INTO Paciente VALUES('#{encrypt 'P14'}', '#{encrypt 'Roberto Gómez' }'   , '#{encrypt 'Av. V. Carranza #54' }' , '#{encrypt '7227652342' }');"
connection.exec "INSERT INTO Paciente VALUES('#{encrypt 'P15'}', '#{encrypt 'Samuel Medina' }'   , '#{encrypt 'Real del bosque #323' }', '#{encrypt '7229182342' }');"
connection.exec "INSERT INTO Paciente VALUES('#{encrypt 'P16'}', '#{encrypt 'Marcelo Robles' }'  , '#{encrypt 'Calle Los Cedros #65' }', '#{encrypt '7222046542' }');"
connection.exec "INSERT INTO Paciente VALUES('#{encrypt 'P17'}', '#{encrypt 'Laura Cárdenas' }'  , '#{encrypt 'Calacoto #234' }'       , '#{encrypt '7221042457' }');"
connection.exec "INSERT INTO Paciente VALUES('#{encrypt 'P18'}', '#{encrypt 'Alejandro Arias' }' , '#{encrypt 'Calle Beni #22' }'      , '#{encrypt '7228487532' }');"
connection.exec "INSERT INTO Paciente VALUES('#{encrypt 'P19'}', '#{encrypt 'Horacio Pérez' }'   , '#{encrypt 'Av. Bánzer #443' }'     , '#{encrypt '7221032356' }');"
connection.exec "INSERT INTO Paciente VALUES('#{encrypt 'P20'}', '#{encrypt 'Alejandro Justiniano' }', '#{encrypt 'Av. Landivar #55' }' , '#{encrypt '7221038234' }');"
connection.exec "INSERT INTO Paciente VALUES('#{encrypt 'P21'}', '#{encrypt 'Ernesto Coimbra' }' , '#{encrypt 'Av. Alemana #23' }'     , '#{encrypt '7221352624' }');"
connection.exec "INSERT INTO Paciente VALUES('#{encrypt 'P22'}', '#{encrypt 'Miguel Ángeles' }'  , '#{encrypt 'Calle Los Pinos #52' }' , '#{encrypt '7227217323' }');"
connection.exec "INSERT INTO Paciente VALUES('#{encrypt 'P23'}', '#{encrypt 'Nicolás Jiménez' }' , '#{encrypt 'Miraflores #123' }'     , '#{encrypt '7221852334' }');"
connection.exec "INSERT INTO Paciente VALUES('#{encrypt 'P24'}', '#{encrypt 'Ramiro Plaza' }'    , '#{encrypt 'Av. V. Carranza #54' }' , '#{encrypt '7227323234' }');"
connection.exec "INSERT INTO Paciente VALUES('#{encrypt 'P25'}', '#{encrypt 'Andrea Ramos' }'    , '#{encrypt 'Real del bosque #323' }', '#{encrypt '7221250312' }');"
connection.exec "INSERT INTO Paciente VALUES('#{encrypt 'P26'}', '#{encrypt 'Carolina Herrera' }', '#{encrypt 'Calle Los Cedros #65' }', '#{encrypt '7225461234' }');"
connection.exec "INSERT INTO Paciente VALUES('#{encrypt 'P27'}', '#{encrypt 'Martha Herrera' }'  , '#{encrypt 'Calacoto #234' }'       , '#{encrypt '7228464578' }');"
connection.exec "INSERT INTO Paciente VALUES('#{encrypt 'P28'}', '#{encrypt 'Alejandro Arias' }' , '#{encrypt 'Calle Beni #22' }'      , '#{encrypt '7222436522' }');"
connection.exec "INSERT INTO Paciente VALUES('#{encrypt 'P29'}', '#{encrypt 'Adriana Pérez' }'   , '#{encrypt 'Av. Bánzer #443' }'     , '#{encrypt '7222534287' }');"
connection.exec "INSERT INTO Paciente VALUES('#{encrypt 'P30'}', '#{encrypt 'Petrona Dorado' }'  , '#{encrypt 'Av. Landívar #55' }'   , '#{encrypt '7225342334' }');"

connection.exec "INSERT INTO AnalisisClinico VALUES('#{encrypt 'A01'}', '#{encrypt 'Sangre'}' , '#{encrypt 'Toma de muestra de sangre'}' );"
connection.exec "INSERT INTO AnalisisClinico VALUES('#{encrypt 'A02'}', '#{encrypt 'Colesterol'}' , '#{encrypt 'Análisis de colesterol del paciente'}' );"
connection.exec "INSERT INTO AnalisisClinico VALUES('#{encrypt 'A03'}', '#{encrypt 'Electrocardiograma'}', '#{encrypt 'El paciente se somete a un electrocardiograma'}');"
connection.exec "INSERT INTO AnalisisClinico VALUES('#{encrypt 'A04'}', '#{encrypt 'Consulta General'}' , '#{encrypt 'Consulta anual del paciente'}');"
connection.exec "INSERT INTO AnalisisClinico VALUES('#{encrypt 'A05'}', '#{encrypt 'Rayos X'}' , '#{encrypt 'Pruebas para doctor externo'}' );"
connection.exec "INSERT INTO AnalisisClinico VALUES('#{encrypt 'A06'}', '#{encrypt 'Antidoping'}' , '#{encrypt 'Análisis de uso de drogas'}' );"
connection.exec "INSERT INTO AnalisisClinico VALUES('#{encrypt 'A07'}', '#{encrypt 'Sangre'}' , '#{encrypt 'Toma de muestra de sangre'}');"
connection.exec "INSERT INTO AnalisisClinico VALUES('#{encrypt 'A08'}', '#{encrypt 'Colesterol'}' , '#{encrypt 'Chequeo de niveles altos decolesterol alto'}' );"
connection.exec "INSERT INTO AnalisisClinico VALUES('#{encrypt 'A09'}', '#{encrypt 'Electrocardiograma'}', '#{encrypt 'Segundo electrocardiograma del paciente'}' );"
connection.exec "INSERT INTO AnalisisClinico VALUES('#{encrypt 'A10'}', '#{encrypt 'Consulta General'}' , '#{encrypt 'Dolores seguidos del paciente'}' );"
connection.exec "INSERT INTO AnalisisClinico VALUES('#{encrypt 'A11'}', '#{encrypt 'Rayos X'}' , '#{encrypt 'Toma de Rayos X de columna'}' );"
connection.exec "INSERT INTO AnalisisClinico VALUES('#{encrypt 'A12'}', '#{encrypt 'Antidoping'}' , '#{encrypt 'Análisis estándar de uso de drogas'}' );"
connection.exec "INSERT INTO AnalisisClinico VALUES('#{encrypt 'A13'}', '#{encrypt 'Radiografía'}' , '#{encrypt 'Radiografía para doctor externo'}' );"
connection.exec "INSERT INTO AnalisisClinico VALUES('#{encrypt 'A14'}', '#{encrypt 'Colesterol'}' , '#{encrypt 'Analisis de niveles decolesterol'}' );"
connection.exec "INSERT INTO AnalisisClinico VALUES('#{encrypt 'A15'}', '#{encrypt 'Electrocardiograma'}', '#{encrypt 'Electrocardiograma para análisis de cáncer'}' );"
connection.exec "INSERT INTO AnalisisClinico VALUES('#{encrypt 'A16'}', '#{encrypt 'Consulta General'}' , '#{encrypt 'Paciente sufre de espasmos'}' );"
connection.exec "INSERT INTO AnalisisClinico VALUES('#{encrypt 'A17'}', '#{encrypt 'Rayos X'}' , '#{encrypt 'Toma de muestra de sangre'}' );"
connection.exec "INSERT INTO AnalisisClinico VALUES('#{encrypt 'A18'}', '#{encrypt 'Angiograma'}' , '#{encrypt 'El paciente se somete a un angiograma'}' );"
connection.exec "INSERT INTO AnalisisClinico VALUES('#{encrypt 'A19'}', '#{encrypt 'Sangre'}' , '#{encrypt 'Toma de muestra de sangre'}' );"
connection.exec "INSERT INTO AnalisisClinico VALUES('#{encrypt 'A20'}', '#{encrypt 'Colesterol'}' , '#{encrypt 'Niveles muy bajos en paciente.'}' );"
connection.exec "INSERT INTO AnalisisClinico VALUES('#{encrypt 'A21'}', '#{encrypt 'Electrocardiograma'}', '#{encrypt 'El paciente se somete a un electrocardiograma'}');"
connection.exec "INSERT INTO AnalisisClinico VALUES('#{encrypt 'A22'}', '#{encrypt 'Radiografía'}' , '#{encrypt 'Dolores en huesos del paciente'}' );"
connection.exec "INSERT INTO AnalisisClinico VALUES('#{encrypt 'A23'}', '#{encrypt 'Colesterol'}' , '#{encrypt 'Análisis de colesterol'}' );"
connection.exec "INSERT INTO AnalisisClinico VALUES('#{encrypt 'A24'}', '#{encrypt 'Radiografía'}' , '#{encrypt 'Radiografía de columna vertebral'}' );"
connection.exec "INSERT INTO AnalisisClinico VALUES('#{encrypt 'A25'}', '#{encrypt 'Embarazo'}' , '#{encrypt 'Toma de muestra de sangre'}' );"
connection.exec "INSERT INTO AnalisisClinico VALUES('#{encrypt 'A26'}', '#{encrypt 'Sangre'}' , '#{encrypt 'Toma de muestra de sangre'}' );"
connection.exec "INSERT INTO AnalisisClinico VALUES('#{encrypt 'A27'}', '#{encrypt 'Electrocardiograma'}', '#{encrypt 'El paciente se somete a un electrocardiograma'}');"
connection.exec "INSERT INTO AnalisisClinico VALUES('#{encrypt 'A28'}', '#{encrypt 'Colesterol'}' , '#{encrypt 'Analisis de niveles de colesterol alto'}' );"
connection.exec "INSERT INTO AnalisisClinico VALUES('#{encrypt 'A29'}', '#{encrypt 'Radiografía'}' , '#{encrypt 'Huesos rotos'}' );"
connection.exec "INSERT INTO AnalisisClinico VALUES('#{encrypt 'A30'}', '#{encrypt 'Rayos X'}' , '#{encrypt 'Toma genérica de Rayos X'}' );"

connection.exec "INSERT INTO Atiende VALUES('#{encrypt 'D01'}', '#{encrypt'P01'}', '#{encrypt'01/03/2011'}', '#{encrypt'Chequeo de rutina'}'   , '#{encrypt'Resfriado'         }');"
connection.exec "INSERT INTO Atiende VALUES('#{encrypt 'D01'}', '#{encrypt'P02'}', '#{encrypt'02/10/2012'}', '#{encrypt'Fisioterapia'}'        , '#{encrypt'Infección'         }');"
connection.exec "INSERT INTO Atiende VALUES('#{encrypt 'D01'}', '#{encrypt'P03'}', '#{encrypt'11/10/2003'}', '#{encrypt'Chequeo de rutina'}'   , '#{encrypt'Leucemia'          }');"
connection.exec "INSERT INTO Atiende VALUES('#{encrypt 'D02'}', '#{encrypt'P04'}', '#{encrypt'12/12/2011'}', '#{encrypt'Fisioterapia'}'        , '#{encrypt'VIH+'              }');"
connection.exec "INSERT INTO Atiende VALUES('#{encrypt 'D02'}', '#{encrypt'P05'}', '#{encrypt'30/05/2012'}', '#{encrypt'Visita rutinaria'}'    , '#{encrypt'Influenza'         }');"
connection.exec "INSERT INTO Atiende VALUES('#{encrypt 'D02'}', '#{encrypt'P06'}', '#{encrypt'12/08/2003'}', '#{encrypt'Visita rutinaria'}'    , '#{encrypt'Malaria'           }');"
connection.exec "INSERT INTO Atiende VALUES('#{encrypt 'D03'}', '#{encrypt'P07'}', '#{encrypt'10/01/2014'}', '#{encrypt'Fisioterapia'}'        , '#{encrypt'Dengue'            }');"
connection.exec "INSERT INTO Atiende VALUES('#{encrypt 'D03'}', '#{encrypt'P08'}', '#{encrypt'20/02/2013'}', '#{encrypt'Chequeo de rutina'}'   , '#{encrypt'Fiebre'            }');"
connection.exec "INSERT INTO Atiende VALUES('#{encrypt 'D03'}', '#{encrypt'P09'}', '#{encrypt'17/01/2013'}', '#{encrypt'Visita rutinaria'}'    , '#{encrypt'Resfriado'         }');"
connection.exec "INSERT INTO Atiende VALUES('#{encrypt 'D04'}', '#{encrypt'P10'}', '#{encrypt'15/11/2012'}', '#{encrypt'Fisioterapia'}'        , '#{encrypt'Cáncer pulmonar'   }');"
connection.exec "INSERT INTO Atiende VALUES('#{encrypt 'D04'}', '#{encrypt'P11'}', '#{encrypt'17/11/2012'}', '#{encrypt'Fisioterapia'}'        , '#{encrypt'Infección'         }');"
connection.exec "INSERT INTO Atiende VALUES('#{encrypt 'D04'}', '#{encrypt'P12'}', '#{encrypt'15/09/2010'}', '#{encrypt'Visita rutinaria'}'    , '#{encrypt'Hérpes'            }');"
connection.exec "INSERT INTO Atiende VALUES('#{encrypt 'D05'}', '#{encrypt'P13'}', '#{encrypt'21/09/2009'}', '#{encrypt'Chequeo de rutina'}'   , '#{encrypt'Fractura Pélvica'  }');"
connection.exec "INSERT INTO Atiende VALUES('#{encrypt 'D05'}', '#{encrypt'P14'}', '#{encrypt'11/11/2011'}', '#{encrypt'Chequeo de rutina'}'   , '#{encrypt'Resfrio'           }');"
connection.exec "INSERT INTO Atiende VALUES('#{encrypt 'D05'}', '#{encrypt'P15'}', '#{encrypt'14/11/2010'}', '#{encrypt'Visita rutinaria'}'    , '#{encrypt'Infección'         }');"
connection.exec "INSERT INTO Atiende VALUES('#{encrypt 'D06'}', '#{encrypt'P16'}', '#{encrypt'11/10/2012'}', '#{encrypt'Chequeo de rutina'}'   , '#{encrypt'Infeccion'         }');"
connection.exec "INSERT INTO Atiende VALUES('#{encrypt 'D06'}', '#{encrypt'P17'}', '#{encrypt'14/02/2011'}', '#{encrypt'Visita rutinaria'}'    , '#{encrypt'Resfriado'         }');"
connection.exec "INSERT INTO Atiende VALUES('#{encrypt 'D06'}', '#{encrypt'P18'}', '#{encrypt'17/01/2013'}', '#{encrypt'Visita rutinaria'}'    , '#{encrypt'Infección'         }');"
connection.exec "INSERT INTO Atiende VALUES('#{encrypt 'D07'}', '#{encrypt'P19'}', '#{encrypt'23/03/2010'}', '#{encrypt'Visita rutinaria'}'    , '#{encrypt'Leucemia'          }');"
connection.exec "INSERT INTO Atiende VALUES('#{encrypt 'D07'}', '#{encrypt'P20'}', '#{encrypt'21/09/2009'}', '#{encrypt'Chequeo de rutina'}'   , '#{encrypt'VIH+'              }');"
connection.exec "INSERT INTO Atiende VALUES('#{encrypt 'D07'}', '#{encrypt'P21'}', '#{encrypt'15/10/2012'}', '#{encrypt'Fisioterapia'}'        , '#{encrypt'Influenza'         }');"
connection.exec "INSERT INTO Atiende VALUES('#{encrypt 'D08'}', '#{encrypt'P22'}', '#{encrypt'10/10/2010'}', '#{encrypt'Visita rutinaria'}'    , '#{encrypt'Malaria'           }');"
connection.exec "INSERT INTO Atiende VALUES('#{encrypt 'D08'}', '#{encrypt'P23'}', '#{encrypt'10/10/2010'}', '#{encrypt'Chequeo de rutina'}'   , '#{encrypt'Dengue'            }');"
connection.exec "INSERT INTO Atiende VALUES('#{encrypt 'D08'}', '#{encrypt'P24'}', '#{encrypt'11/11/2011'}', '#{encrypt'Visita rutinaria'}'    , '#{encrypt'Fiebre'            }');"
connection.exec "INSERT INTO Atiende VALUES('#{encrypt 'D09'}', '#{encrypt'P25'}', '#{encrypt'19/05/2009'}', '#{encrypt'Fisioterapia'}'        , '#{encrypt'Resfriado'         }');"
connection.exec "INSERT INTO Atiende VALUES('#{encrypt 'D09'}', '#{encrypt'P26'}', '#{encrypt'16/04/2012'}', '#{encrypt'Visita rutinaria'}'    , '#{encrypt'Cáncer pulmonar'   }');"
connection.exec "INSERT INTO Atiende VALUES('#{encrypt 'D09'}', '#{encrypt'P27'}', '#{encrypt'21/12/2012'}', '#{encrypt'Fisioterapia'}'	       , '#{encrypt'Neurosífilis'      }');"
connection.exec "INSERT INTO Atiende VALUES('#{encrypt 'D10'}', '#{encrypt'P28'}', '#{encrypt'15/10/2009'}', '#{encrypt'Vitita rutinaria'}'    , '#{encrypt'Hérpes'            }');"
connection.exec "INSERT INTO Atiende VALUES('#{encrypt 'D10'}', '#{encrypt'P29'}', '#{encrypt'12/03/2013'}', '#{encrypt'Visita rutinaria'}'    , '#{encrypt'Fractura Pélvica'  }');"
connection.exec "INSERT INTO Atiende VALUES('#{encrypt 'D10'}', '#{encrypt'P30'}', '#{encrypt'12/03/2013'}', '#{encrypt'Chequeo de rutina'}'   , '#{encrypt'Fiebre'            }');"
connection.exec "INSERT INTO Atiende VALUES('#{encrypt 'D11'}', '#{encrypt'P01'}', '#{encrypt'01/03/2010'}', '#{encrypt'Chequeo de rutina'}'   , '#{encrypt'Dolor de Cabeza'   }');"
connection.exec "INSERT INTO Atiende VALUES('#{encrypt 'D11'}', '#{encrypt'P02'}', '#{encrypt'02/10/2012'}', '#{encrypt'Fisioterapia'}'        , '#{encrypt'Cáncer'            }');"
connection.exec "INSERT INTO Atiende VALUES('#{encrypt 'D11'}', '#{encrypt'P03'}', '#{encrypt'11/10/2009'}', '#{encrypt'Chequeo de rutina'}'   , '#{encrypt'Fractura'          }');"
connection.exec "INSERT INTO Atiende VALUES('#{encrypt 'D12'}', '#{encrypt'P01'}', '#{encrypt'12/12/2012'}', '#{encrypt'Fisioterapia'}'        , '#{encrypt'Dengue'            }');"
connection.exec "INSERT INTO Atiende VALUES('#{encrypt 'D12'}', '#{encrypt'P02'}', '#{encrypt'30/05/2011'}', '#{encrypt'Visita rutinaria'}'    , '#{encrypt'Infeccion'    }');"
connection.exec "INSERT INTO Atiende VALUES('#{encrypt 'D12'}', '#{encrypt'P03'}', '#{encrypt'12/08/2008'}', '#{encrypt'Visita rutinaria'}'    , '#{encrypt'Infeccion'    }');"
connection.exec "INSERT INTO Atiende VALUES('#{encrypt 'D13'}', '#{encrypt'P01'}', '#{encrypt'10/01/2013'}', '#{encrypt'Fisioterapia'}'        , '#{encrypt'Fractura'     }');"
connection.exec "INSERT INTO Atiende VALUES('#{encrypt 'D13'}', '#{encrypt'P02'}', '#{encrypt'20/02/2013'}', '#{encrypt'Chequeo de rutina'}'   , '#{encrypt'Malaria'      }');"
connection.exec "INSERT INTO Atiende VALUES('#{encrypt 'D13'}', '#{encrypt'P03'}', '#{encrypt'17/01/2013'}', '#{encrypt'Visita rutinaria'}'    , '#{encrypt'Fractura'     }');"
connection.exec "INSERT INTO Atiende VALUES('#{encrypt 'D14'}', '#{encrypt'P04'}', '#{encrypt'15/11/2012'}', '#{encrypt'Fisioterapia'}'        , '#{encrypt'Resfrio'      }');"
connection.exec "INSERT INTO Atiende VALUES('#{encrypt 'D14'}', '#{encrypt'P05'}', '#{encrypt'17/11/2012'}', '#{encrypt'Fisioterapia'}'        , '#{encrypt'Lepra'        }');"
connection.exec "INSERT INTO Atiende VALUES('#{encrypt 'D14'}', '#{encrypt'P06'}', '#{encrypt'15/09/2010'}', '#{encrypt'Visita rutinaria'}'    , '#{encrypt'Fractura'     }');"
connection.exec "INSERT INTO Atiende VALUES('#{encrypt 'D15'}', '#{encrypt'P04'}', '#{encrypt'21/09/2009'}', '#{encrypt'Chequeo de rutina'}'   , '#{encrypt'Resfrio'      }');"
connection.exec "INSERT INTO Atiende VALUES('#{encrypt 'D15'}', '#{encrypt'P05'}', '#{encrypt'11/11/2011'}', '#{encrypt'Chequeo de rutina'}'   , '#{encrypt'Resfrio'  	   }');"
connection.exec "INSERT INTO Atiende VALUES('#{encrypt 'D15'}', '#{encrypt'P06'}', '#{encrypt'14/11/2010'}', '#{encrypt'Visita rutinaria'}'    , '#{encrypt'Fractura'     }');"
connection.exec "INSERT INTO Atiende VALUES('#{encrypt 'D16'}', '#{encrypt'P04'}', '#{encrypt'11/10/2012'}', '#{encrypt'Chequeo de rutina'}'   , '#{encrypt'Infeccion'    }');"
connection.exec "INSERT INTO Atiende VALUES('#{encrypt 'D16'}', '#{encrypt'P05'}', '#{encrypt'14/02/2011'}', '#{encrypt'Visita rutinaria'}'    , '#{encrypt'Inflamacion'  }');"
connection.exec "INSERT INTO Atiende VALUES('#{encrypt 'D16'}', '#{encrypt'P06'}', '#{encrypt'17/01/2013'}', '#{encrypt'Visita rutinaria'}'    , '#{encrypt'Mal de Ojo'   }');"
connection.exec "INSERT INTO Atiende VALUES('#{encrypt 'D17'}', '#{encrypt'P23'}', '#{encrypt'23/03/2010'}', '#{encrypt'Visita rutinaria'}'    , '#{encrypt'Resfrio'      }');"
connection.exec "INSERT INTO Atiende VALUES('#{encrypt 'D17'}', '#{encrypt'P30'}', '#{encrypt'21/09/2009'}', '#{encrypt'Chequeo de rutina'}'   , '#{encrypt'Inflamacion'  }');"
connection.exec "INSERT INTO Atiende VALUES('#{encrypt 'D17'}', '#{encrypt'P30'}', '#{encrypt'15/10/2012'}', '#{encrypt'Fisioterapia'}'        , '#{encrypt'Fractura'     }');"
connection.exec "INSERT INTO Atiende VALUES('#{encrypt 'D18'}', '#{encrypt'P21'}', '#{encrypt'10/10/2010'}', '#{encrypt'Visita rutinaria'}'    , '#{encrypt'Infeccion'    }');"
connection.exec "INSERT INTO Atiende VALUES('#{encrypt 'D18'}', '#{encrypt'P12'}', '#{encrypt'10/10/2010'}', '#{encrypt'Chequeo de rutina'}'   , '#{encrypt'Inflamacion'  }');"
connection.exec "INSERT INTO Atiende VALUES('#{encrypt 'D18'}', '#{encrypt'P23'}', '#{encrypt'11/11/2011'}', '#{encrypt'Visita rutinaria'}'    , '#{encrypt'Inflamacion'  }');"
connection.exec "INSERT INTO Atiende VALUES('#{encrypt 'D19'}', '#{encrypt'P24'}', '#{encrypt'19/05/2009'}', '#{encrypt'Fisioterapia'}'        , '#{encrypt'Infeccion'    }');"
connection.exec "INSERT INTO Atiende VALUES('#{encrypt 'D19'}', '#{encrypt'P15'}', '#{encrypt'16/04/2012'}', '#{encrypt'Visita rutinaria'}'    , '#{encrypt'Inflamacion'  }');"
connection.exec "INSERT INTO Atiende VALUES('#{encrypt 'D19'}', '#{encrypt'P16'}', '#{encrypt'21/12/2012'}', '#{encrypt'Fisioterapia'}'	       , '#{encrypt'Resfrio'      }');"
connection.exec "INSERT INTO Atiende VALUES('#{encrypt 'D20'}', '#{encrypt'P17'}', '#{encrypt'15/10/2009'}', '#{encrypt'Visita rutinaria'}'    , '#{encrypt'Polio'        }');"
connection.exec "INSERT INTO Atiende VALUES('#{encrypt 'D20'}', '#{encrypt'P18'}', '#{encrypt'12/03/2013'}', '#{encrypt'Visita rutinaria'}'    , '#{encrypt'Infeccion'    }');"
connection.exec "INSERT INTO Atiende VALUES('#{encrypt 'D20'}', '#{encrypt'P19'}', '#{encrypt'12/03/2013'}', '#{encrypt'Chequeo de rutina'}'   , '#{encrypt'Fractura'     }');"
connection.exec "INSERT INTO Atiende VALUES('#{encrypt 'D21'}', '#{encrypt'P10'}', '#{encrypt'01/03/2010'}', '#{encrypt'Chequeo de rutina'}'   , '#{encrypt'Resfrio'      }');"
connection.exec "INSERT INTO Atiende VALUES('#{encrypt 'D21'}', '#{encrypt'P21'}', '#{encrypt'02/10/2012'}', '#{encrypt'Fisioterapia'}'        , '#{encrypt'Infeccion'    }');"
connection.exec "INSERT INTO Atiende VALUES('#{encrypt 'D21'}', '#{encrypt'P30'}', '#{encrypt'11/10/2009'}', '#{encrypt'Chequeo de rutina'}'   , '#{encrypt'Fractura'     }');"
connection.exec "INSERT INTO Atiende VALUES('#{encrypt 'D22'}', '#{encrypt'P22'}', '#{encrypt'12/12/2012'}', '#{encrypt'Fisioterapia'}'        , '#{encrypt'Resfrio'      }');"
connection.exec "INSERT INTO Atiende VALUES('#{encrypt 'D22'}', '#{encrypt'P13'}', '#{encrypt'30/05/2011'}', '#{encrypt'Visita rutinaria'}'    , '#{encrypt'Infeccion'    }');"
connection.exec "INSERT INTO Atiende VALUES('#{encrypt 'D22'}', '#{encrypt'P24'}', '#{encrypt'12/08/2008'}', '#{encrypt'Visita rutinaria'}'    , '#{encrypt'Infeccion'    }');"
connection.exec "INSERT INTO Atiende VALUES('#{encrypt 'D23'}', '#{encrypt'P25'}', '#{encrypt'10/01/2013'}', '#{encrypt'Fisioterapia'}'        , '#{encrypt'Fractura'     }');"
connection.exec "INSERT INTO Atiende VALUES('#{encrypt 'D23'}', '#{encrypt'P06'}', '#{encrypt'20/02/2013'}', '#{encrypt'Chequeo de rutina'}'   , '#{encrypt'Resfrio'      }');"
connection.exec "INSERT INTO Atiende VALUES('#{encrypt 'D23'}', '#{encrypt'P07'}', '#{encrypt'17/01/2013'}', '#{encrypt'Visita rutinaria'}'    , '#{encrypt'Fractura'     }');"
connection.exec "INSERT INTO Atiende VALUES('#{encrypt 'D24'}', '#{encrypt'P08'}', '#{encrypt'15/11/2012'}', '#{encrypt'Fisioterapia'}'        , '#{encrypt'Resfrio'      }');"
connection.exec "INSERT INTO Atiende VALUES('#{encrypt 'D24'}', '#{encrypt'P19'}', '#{encrypt'17/11/2012'}', '#{encrypt'Fisioterapia'}'        , '#{encrypt'Resfrio'      }');"
connection.exec "INSERT INTO Atiende VALUES('#{encrypt 'D24'}', '#{encrypt'P10'}', '#{encrypt'15/09/2010'}', '#{encrypt'Visita rutinaria'}'    , '#{encrypt'Fractura'     }');"
connection.exec "INSERT INTO Atiende VALUES('#{encrypt 'D25'}', '#{encrypt'P01'}', '#{encrypt'21/09/2009'}', '#{encrypt'Chequeo de rutina'}'   , '#{encrypt'Resfrio'      }');"
connection.exec "INSERT INTO Atiende VALUES('#{encrypt 'D25'}', '#{encrypt'P22'}', '#{encrypt'11/11/2011'}', '#{encrypt'Chequeo de rutina'}'   , '#{encrypt'Resfrio'  	   }');"
connection.exec "INSERT INTO Atiende VALUES('#{encrypt 'D25'}', '#{encrypt'P23'}', '#{encrypt'14/11/2010'}', '#{encrypt'Visita rutinaria'}'    , '#{encrypt'Fractura'     }');"
connection.exec "INSERT INTO Atiende VALUES('#{encrypt 'D26'}', '#{encrypt'P14'}', '#{encrypt'11/10/2012'}', '#{encrypt'Chequeo de rutina'}'   , '#{encrypt'Infeccion'    }');"
connection.exec "INSERT INTO Atiende VALUES('#{encrypt 'D26'}', '#{encrypt'P25'}', '#{encrypt'14/02/2011'}', '#{encrypt'Visita rutinaria'}'    , '#{encrypt'Inflamacion'  }');"
connection.exec "INSERT INTO Atiende VALUES('#{encrypt 'D26'}', '#{encrypt'P16'}', '#{encrypt'17/01/2013'}', '#{encrypt'Visita rutinaria'}'    , '#{encrypt'Fractura'     }');"
connection.exec "INSERT INTO Atiende VALUES('#{encrypt 'D27'}', '#{encrypt'P27'}', '#{encrypt'23/03/2010'}', '#{encrypt'Visita rutinaria'}'    , '#{encrypt'Resfrio'      }');"
connection.exec "INSERT INTO Atiende VALUES('#{encrypt 'D27'}', '#{encrypt'P08'}', '#{encrypt'21/09/2009'}', '#{encrypt'Chequeo de rutina'}'   , '#{encrypt'Inflamacion'  }');"
connection.exec "INSERT INTO Atiende VALUES('#{encrypt 'D27'}', '#{encrypt'P09'}', '#{encrypt'15/10/2012'}', '#{encrypt'Fisioterapia'}'        , '#{encrypt'Fractura'     }');"
connection.exec "INSERT INTO Atiende VALUES('#{encrypt 'D28'}', '#{encrypt'P07'}', '#{encrypt'10/10/2010'}', '#{encrypt'Visita rutinaria'}'    , '#{encrypt'Infeccion'    }');"
connection.exec "INSERT INTO Atiende VALUES('#{encrypt 'D28'}', '#{encrypt'P01'}', '#{encrypt'10/10/2010'}', '#{encrypt'Chequeo de rutina'}'   , '#{encrypt'VIH+'         }');"
connection.exec "INSERT INTO Atiende VALUES('#{encrypt 'D28'}', '#{encrypt'P02'}', '#{encrypt'11/11/2011'}', '#{encrypt'Visita rutinaria'}'    , '#{encrypt'Inflamacion'  }');"
connection.exec "INSERT INTO Atiende VALUES('#{encrypt 'D29'}', '#{encrypt'P03'}', '#{encrypt'19/05/2009'}', '#{encrypt'Fisioterapia'}'        , '#{encrypt'Infeccion'    }');"
connection.exec "INSERT INTO Atiende VALUES('#{encrypt 'D29'}', '#{encrypt'P24'}', '#{encrypt'16/04/2012'}', '#{encrypt'Visita rutinaria'}'    , '#{encrypt'Inflamacion'  }');"
connection.exec "INSERT INTO Atiende VALUES('#{encrypt 'D29'}', '#{encrypt'P05'}', '#{encrypt'21/12/2012'}', '#{encrypt'Fisioterapia'}'	       , '#{encrypt'Resfrio'      }');"
connection.exec "INSERT INTO Atiende VALUES('#{encrypt 'D30'}', '#{encrypt'P26'}', '#{encrypt'15/10/2009'}', '#{encrypt'Visita rutinaria'}'    , '#{encrypt'Inflamacion'  }');"
connection.exec "INSERT INTO Atiende VALUES('#{encrypt 'D30'}', '#{encrypt'P27'}', '#{encrypt'12/03/2013'}', '#{encrypt'Visita rutinaria'}'    , '#{encrypt'Infeccion'    }');"
connection.exec "INSERT INTO Atiende VALUES('#{encrypt 'D30'}', '#{encrypt'P28'}', '#{encrypt'12/03/2013'}', '#{encrypt'Chequeo de rutina'}'   , '#{encrypt'Fractura'     }');"

connection.exec "INSERT INTO SeRealiza VALUES  ('#{encrypt 'A07'}','#{encrypt 'P19'}','#{encrypt '08/07/2010'}','#{encrypt '15/07/2010'}');"
connection.exec "INSERT INTO SeRealiza VALUES  ('#{encrypt 'A20'}','#{encrypt 'P22'}','#{encrypt '05/07/2010'}','#{encrypt '21/07/2010'}');"
connection.exec "INSERT INTO SeRealiza VALUES  ('#{encrypt 'A17'}','#{encrypt 'P04'}','#{encrypt '08/07/2010'}','#{encrypt '20/07/2010'}');"
connection.exec "INSERT INTO SeRealiza VALUES  ('#{encrypt 'A17'}','#{encrypt 'P08'}','#{encrypt '08/07/2010'}','#{encrypt '17/07/2010'}');"
connection.exec "INSERT INTO SeRealiza VALUES  ('#{encrypt 'A11'}','#{encrypt 'P23'}','#{encrypt '14/07/2010'}','#{encrypt '18/07/2010'}');"
connection.exec "INSERT INTO SeRealiza VALUES  ('#{encrypt 'A28'}','#{encrypt 'P20'}','#{encrypt '05/07/2010'}','#{encrypt '19/07/2010'}');"
connection.exec "INSERT INTO SeRealiza VALUES  ('#{encrypt 'A02'}','#{encrypt 'P11'}','#{encrypt '14/07/2010'}','#{encrypt '19/07/2010'}');"
connection.exec "INSERT INTO SeRealiza VALUES  ('#{encrypt 'A17'}','#{encrypt 'P05'}','#{encrypt '06/07/2010'}','#{encrypt '19/07/2010'}');"
connection.exec "INSERT INTO SeRealiza VALUES  ('#{encrypt 'A27'}','#{encrypt 'P30'}','#{encrypt '11/07/2010'}','#{encrypt '17/07/2010'}');"
connection.exec "INSERT INTO SeRealiza VALUES  ('#{encrypt 'A28'}','#{encrypt 'P17'}','#{encrypt '07/07/2010'}','#{encrypt '19/07/2010'}');"
connection.exec "INSERT INTO SeRealiza VALUES  ('#{encrypt 'A20'}','#{encrypt 'P23'}','#{encrypt '14/07/2010'}','#{encrypt '18/07/2010'}');"
connection.exec "INSERT INTO SeRealiza VALUES  ('#{encrypt 'A29'}','#{encrypt 'P09'}','#{encrypt '14/07/2010'}','#{encrypt '17/07/2010'}');"
connection.exec "INSERT INTO SeRealiza VALUES  ('#{encrypt 'A25'}','#{encrypt 'P06'}','#{encrypt '13/07/2010'}','#{encrypt '16/07/2010'}');"
connection.exec "INSERT INTO SeRealiza VALUES  ('#{encrypt 'A18'}','#{encrypt 'P03'}','#{encrypt '12/07/2010'}','#{encrypt '19/07/2010'}');"
connection.exec "INSERT INTO SeRealiza VALUES  ('#{encrypt 'A30'}','#{encrypt 'P20'}','#{encrypt '07/07/2010'}','#{encrypt '19/07/2010'}');"
connection.exec "INSERT INTO SeRealiza VALUES  ('#{encrypt 'A06'}','#{encrypt 'P25'}','#{encrypt '05/07/2010'}','#{encrypt '17/07/2010'}');"
connection.exec "INSERT INTO SeRealiza VALUES  ('#{encrypt 'A30'}','#{encrypt 'P11'}','#{encrypt '06/07/2010'}','#{encrypt '15/07/2010'}');"
connection.exec "INSERT INTO SeRealiza VALUES  ('#{encrypt 'A24'}','#{encrypt 'P24'}','#{encrypt '08/07/2010'}','#{encrypt '19/07/2010'}');"
connection.exec "INSERT INTO SeRealiza VALUES  ('#{encrypt 'A26'}','#{encrypt 'P28'}','#{encrypt '12/07/2010'}','#{encrypt '20/07/2010'}');"
connection.exec "INSERT INTO SeRealiza VALUES  ('#{encrypt 'A09'}','#{encrypt 'P07'}','#{encrypt '10/07/2010'}','#{encrypt '21/07/2010'}');"
connection.exec "INSERT INTO SeRealiza VALUES  ('#{encrypt 'A08'}','#{encrypt 'P08'}','#{encrypt '11/07/2010'}','#{encrypt '20/07/2010'}');"
connection.exec "INSERT INTO SeRealiza VALUES  ('#{encrypt 'A11'}','#{encrypt 'P28'}','#{encrypt '09/07/2010'}','#{encrypt '16/07/2010'}');"
connection.exec "INSERT INTO SeRealiza VALUES  ('#{encrypt 'A06'}','#{encrypt 'P05'}','#{encrypt '10/07/2010'}','#{encrypt '17/07/2010'}');"
connection.exec "INSERT INTO SeRealiza VALUES  ('#{encrypt 'A03'}','#{encrypt 'P08'}','#{encrypt '10/07/2010'}','#{encrypt '18/07/2010'}');"
connection.exec "INSERT INTO SeRealiza VALUES  ('#{encrypt 'A15'}','#{encrypt 'P08'}','#{encrypt '12/07/2010'}','#{encrypt '20/07/2010'}');"
connection.exec "INSERT INTO SeRealiza VALUES  ('#{encrypt 'A06'}','#{encrypt 'P04'}','#{encrypt '11/07/2010'}','#{encrypt '16/07/2010'}');"
connection.exec "INSERT INTO SeRealiza VALUES  ('#{encrypt 'A03'}','#{encrypt 'P27'}','#{encrypt '06/07/2010'}','#{encrypt '20/07/2010'}');"
connection.exec "INSERT INTO SeRealiza VALUES  ('#{encrypt 'A14'}','#{encrypt 'P20'}','#{encrypt '06/07/2010'}','#{encrypt '15/07/2010'}');"
connection.exec "INSERT INTO SeRealiza VALUES  ('#{encrypt 'A03'}','#{encrypt 'P07'}','#{encrypt '06/07/2010'}','#{encrypt '17/07/2010'}');"
connection.exec "INSERT INTO SeRealiza VALUES  ('#{encrypt 'A16'}','#{encrypt 'P24'}','#{encrypt '04/07/2010'}','#{encrypt '21/07/2010'}');"
connection.exec "INSERT INTO SeRealiza VALUES  ('#{encrypt 'A16'}','#{encrypt 'P18'}','#{encrypt '11/09/2012'}','#{encrypt '04/11/2012'}');"
connection.exec "INSERT INTO SeRealiza VALUES  ('#{encrypt 'A29'}','#{encrypt 'P29'}','#{encrypt '22/09/2012'}','#{encrypt '05/11/2012'}');"
connection.exec "INSERT INTO SeRealiza VALUES  ('#{encrypt 'A09'}','#{encrypt 'P14'}','#{encrypt '19/09/2012'}','#{encrypt '23/10/2012'}');"
connection.exec "INSERT INTO SeRealiza VALUES  ('#{encrypt 'A25'}','#{encrypt 'P18'}','#{encrypt '23/09/2012'}','#{encrypt '25/10/2012'}');"
connection.exec "INSERT INTO SeRealiza VALUES  ('#{encrypt 'A17'}','#{encrypt 'P06'}','#{encrypt '04/10/2012'}','#{encrypt '06/11/2012'}');"
connection.exec "INSERT INTO SeRealiza VALUES  ('#{encrypt 'A23'}','#{encrypt 'P08'}','#{encrypt '29/09/2012'}','#{encrypt '13/11/2012'}');"
connection.exec "INSERT INTO SeRealiza VALUES  ('#{encrypt 'A27'}','#{encrypt 'P13'}','#{encrypt '15/09/2012'}','#{encrypt '09/11/2012'}');"
connection.exec "INSERT INTO SeRealiza VALUES  ('#{encrypt 'A14'}','#{encrypt 'P03'}','#{encrypt '30/09/2012'}','#{encrypt '28/10/2012'}');"
connection.exec "INSERT INTO SeRealiza VALUES  ('#{encrypt 'A26'}','#{encrypt 'P18'}','#{encrypt '07/10/2012'}','#{encrypt '12/11/2012'}');"
connection.exec "INSERT INTO SeRealiza VALUES  ('#{encrypt 'A01'}','#{encrypt 'P02'}','#{encrypt '27/09/2012'}','#{encrypt '13/11/2012'}');"
connection.exec "INSERT INTO SeRealiza VALUES  ('#{encrypt 'A30'}','#{encrypt 'P27'}','#{encrypt '25/09/2012'}','#{encrypt '26/10/2012'}');"
connection.exec "INSERT INTO SeRealiza VALUES  ('#{encrypt 'A03'}','#{encrypt 'P15'}','#{encrypt '16/09/2012'}','#{encrypt '02/11/2012'}');"
connection.exec "INSERT INTO SeRealiza VALUES  ('#{encrypt 'A28'}','#{encrypt 'P17'}','#{encrypt '11/10/2012'}','#{encrypt '29/10/2012'}');"
connection.exec "INSERT INTO SeRealiza VALUES  ('#{encrypt 'A08'}','#{encrypt 'P06'}','#{encrypt '09/10/2012'}','#{encrypt '28/10/2012'}');"
connection.exec "INSERT INTO SeRealiza VALUES  ('#{encrypt 'A21'}','#{encrypt 'P25'}','#{encrypt '16/09/2012'}','#{encrypt '16/10/2012'}');"
connection.exec "INSERT INTO SeRealiza VALUES  ('#{encrypt 'A02'}','#{encrypt 'P10'}','#{encrypt '21/09/2012'}','#{encrypt '05/11/2012'}');"
connection.exec "INSERT INTO SeRealiza VALUES  ('#{encrypt 'A05'}','#{encrypt 'P13'}','#{encrypt '02/10/2012'}','#{encrypt '20/10/2012'}');"
connection.exec "INSERT INTO SeRealiza VALUES  ('#{encrypt 'A24'}','#{encrypt 'P14'}','#{encrypt '14/10/2012'}','#{encrypt '11/11/2012'}');"
connection.exec "INSERT INTO SeRealiza VALUES  ('#{encrypt 'A25'}','#{encrypt 'P28'}','#{encrypt '26/09/2012'}','#{encrypt '12/11/2012'}');"
connection.exec "INSERT INTO SeRealiza VALUES  ('#{encrypt 'A14'}','#{encrypt 'P25'}','#{encrypt '27/09/2012'}','#{encrypt '17/10/2012'}');"
connection.exec "INSERT INTO SeRealiza VALUES  ('#{encrypt 'A06'}','#{encrypt 'P12'}','#{encrypt '20/09/2012'}','#{encrypt '09/11/2012'}');"
connection.exec "INSERT INTO SeRealiza VALUES  ('#{encrypt 'A23'}','#{encrypt 'P01'}','#{encrypt '05/10/2012'}','#{encrypt '29/10/2012'}');"
connection.exec "INSERT INTO SeRealiza VALUES  ('#{encrypt 'A29'}','#{encrypt 'P12'}','#{encrypt '11/09/2012'}','#{encrypt '03/11/2012'}');"
connection.exec "INSERT INTO SeRealiza VALUES  ('#{encrypt 'A01'}','#{encrypt 'P27'}','#{encrypt '02/10/2012'}','#{encrypt '23/10/2012'}');"
connection.exec "INSERT INTO SeRealiza VALUES  ('#{encrypt 'A03'}','#{encrypt 'P28'}','#{encrypt '11/09/2012'}','#{encrypt '20/10/2012'}');"
connection.exec "INSERT INTO SeRealiza VALUES  ('#{encrypt 'A30'}','#{encrypt 'P19'}','#{encrypt '22/09/2012'}','#{encrypt '03/11/2012'}');"
connection.exec "INSERT INTO SeRealiza VALUES  ('#{encrypt 'A18'}','#{encrypt 'P10'}','#{encrypt '22/09/2012'}','#{encrypt '26/10/2012'}');"
connection.exec "INSERT INTO SeRealiza VALUES  ('#{encrypt 'A11'}','#{encrypt 'P29'}','#{encrypt '20/09/2012'}','#{encrypt '02/11/2012'}');"
connection.exec "INSERT INTO SeRealiza VALUES  ('#{encrypt 'A20'}','#{encrypt 'P17'}','#{encrypt '24/09/2012'}','#{encrypt '03/11/2012'}');"
connection.exec "INSERT INTO SeRealiza VALUES  ('#{encrypt 'A02'}','#{encrypt 'P26'}','#{encrypt '02/10/2012'}','#{encrypt '19/10/2012'}');"
connection.exec "INSERT INTO SeRealiza VALUES  ('#{encrypt 'A20'}','#{encrypt 'P05'}','#{encrypt '08/01/2013'}','#{encrypt '14/08/2013'}');"
connection.exec "INSERT INTO SeRealiza VALUES  ('#{encrypt 'A22'}','#{encrypt 'P11'}','#{encrypt '23/04/2013'}','#{encrypt '03/10/2013'}');"
connection.exec "INSERT INTO SeRealiza VALUES  ('#{encrypt 'A17'}','#{encrypt 'P12'}','#{encrypt '09/09/2012'}','#{encrypt '18/08/2013'}');"
connection.exec "INSERT INTO SeRealiza VALUES  ('#{encrypt 'A10'}','#{encrypt 'P26'}','#{encrypt '21/05/2013'}','#{encrypt '18/06/2013'}');"
connection.exec "INSERT INTO SeRealiza VALUES  ('#{encrypt 'A05'}','#{encrypt 'P06'}','#{encrypt '27/12/2012'}','#{encrypt '16/09/2013'}');"
connection.exec "INSERT INTO SeRealiza VALUES  ('#{encrypt 'A09'}','#{encrypt 'P04'}','#{encrypt '16/02/2013'}','#{encrypt '24/06/2013'}');"
connection.exec "INSERT INTO SeRealiza VALUES  ('#{encrypt 'A03'}','#{encrypt 'P30'}','#{encrypt '08/04/2013'}','#{encrypt '28/07/2013'}');"
connection.exec "INSERT INTO SeRealiza VALUES  ('#{encrypt 'A18'}','#{encrypt 'P24'}','#{encrypt '01/09/2012'}','#{encrypt '27/06/2013'}');"
connection.exec "INSERT INTO SeRealiza VALUES  ('#{encrypt 'A06'}','#{encrypt 'P08'}','#{encrypt '12/02/2013'}','#{encrypt '28/08/2013'}');"
connection.exec "INSERT INTO SeRealiza VALUES  ('#{encrypt 'A27'}','#{encrypt 'P21'}','#{encrypt '23/01/2013'}','#{encrypt '19/06/2013'}');"
connection.exec "INSERT INTO SeRealiza VALUES  ('#{encrypt 'A09'}','#{encrypt 'P01'}','#{encrypt '29/12/2012'}','#{encrypt '19/08/2013'}');"
connection.exec "INSERT INTO SeRealiza VALUES  ('#{encrypt 'A16'}','#{encrypt 'P26'}','#{encrypt '23/03/2013'}','#{encrypt '27/09/2013'}');"
connection.exec "INSERT INTO SeRealiza VALUES  ('#{encrypt 'A25'}','#{encrypt 'P05'}','#{encrypt '18/08/2012'}','#{encrypt '10/07/2013'}');"
connection.exec "INSERT INTO SeRealiza VALUES  ('#{encrypt 'A22'}','#{encrypt 'P19'}','#{encrypt '25/01/2013'}','#{encrypt '12/09/2013'}');"
connection.exec "INSERT INTO SeRealiza VALUES  ('#{encrypt 'A21'}','#{encrypt 'P28'}','#{encrypt '07/04/2013'}','#{encrypt '09/07/2013'}');"
connection.exec "INSERT INTO SeRealiza VALUES  ('#{encrypt 'A12'}','#{encrypt 'P21'}','#{encrypt '31/10/2012'}','#{encrypt '17/08/2013'}');"
connection.exec "INSERT INTO SeRealiza VALUES  ('#{encrypt 'A21'}','#{encrypt 'P19'}','#{encrypt '09/03/2013'}','#{encrypt '29/06/2013'}');"
connection.exec "INSERT INTO SeRealiza VALUES  ('#{encrypt 'A13'}','#{encrypt 'P20'}','#{encrypt '08/11/2012'}','#{encrypt '07/07/2013'}');"
connection.exec "INSERT INTO SeRealiza VALUES  ('#{encrypt 'A24'}','#{encrypt 'P18'}','#{encrypt '07/10/2012'}','#{encrypt '10/08/2013'}');"
connection.exec "INSERT INTO SeRealiza VALUES  ('#{encrypt 'A11'}','#{encrypt 'P05'}','#{encrypt '30/01/2013'}','#{encrypt '04/08/2013'}');"
connection.exec "INSERT INTO SeRealiza VALUES  ('#{encrypt 'A14'}','#{encrypt 'P17'}','#{encrypt '27/04/2013'}','#{encrypt '12/07/2013'}');"
connection.exec "INSERT INTO SeRealiza VALUES  ('#{encrypt 'A03'}','#{encrypt 'P09'}','#{encrypt '19/07/2012'}','#{encrypt '18/09/2013'}');"
connection.exec "INSERT INTO SeRealiza VALUES  ('#{encrypt 'A10'}','#{encrypt 'P27'}','#{encrypt '25/12/2012'}','#{encrypt '16/07/2013'}');"
connection.exec "INSERT INTO SeRealiza VALUES  ('#{encrypt 'A11'}','#{encrypt 'P16'}','#{encrypt '13/10/2012'}','#{encrypt '30/09/2013'}');"
connection.exec "INSERT INTO SeRealiza VALUES  ('#{encrypt 'A16'}','#{encrypt 'P06'}','#{encrypt '20/07/2012'}','#{encrypt '19/07/2013'}');"
connection.exec "INSERT INTO SeRealiza VALUES  ('#{encrypt 'A29'}','#{encrypt 'P12'}','#{encrypt '07/12/2012'}','#{encrypt '29/07/2013'}');"
connection.exec "INSERT INTO SeRealiza VALUES  ('#{encrypt 'A09'}','#{encrypt 'P12'}','#{encrypt '01/06/2013'}','#{encrypt '21/07/2013'}');"
connection.exec "INSERT INTO SeRealiza VALUES  ('#{encrypt 'A01'}','#{encrypt 'P01'}','#{encrypt '23/04/2013'}','#{encrypt '10/06/2013'}');"
connection.exec "INSERT INTO SeRealiza VALUES  ('#{encrypt 'A08'}','#{encrypt 'P27'}','#{encrypt '13/02/2013'}','#{encrypt '21/09/2013'}');"
connection.exec "INSERT INTO SeRealiza VALUES  ('#{encrypt 'A12'}','#{encrypt 'P09'}','#{encrypt '09/08/2012'}','#{encrypt '19/08/2013'}');"